### PR TITLE
Add clone() methods to AsepriteSpriteSheet and AsepriteResource

### LINKED ISSUE #126: Add a way to get a new spritesheet/animation reference from resource
### Context
Consider a scenario in which you are reusing an animation from the same Aseprite resource on multiple actors. The animation returned from `getAnimation()` is shared, so the playback state is also shared across all actors using the same Aseprite resource.

https://codesandbox.io/s/excalibur-aseprite-shared-animation-reference-wjhuo8?file=/index.js

In the above example, there are 2 actors that should start on different frames of the same animation. Without the commented workaround, they share the animation state.

### Proposal
Accept a parameter in `resource.getAnimation()` or `getSpritesheet()` that returns a new instance of the spritesheet or animation.

```js
resource.getAnimation('abc', true)
resource.getSpriteSheet(true).getAnimation('abc')
```

I prefer the former, but I think having both would be good if you ever need the actual spritesheet reference too. 

I'm happy to make a PR for this. I'm just unsure what to call the parameter. `new` is a keyword so probably not that. `recreate`?

### PR DESCRIPTION
**Pull request by mattjennings**
===:clipboard: PR Checklist :clipboard:===

- [x] :pushpin: issue exists in github for these changes
- [x] :microscope: existing tests still pass
- [x] :see_no_evil: code conforms to the [style guide](https://github.com/excaliburjs/Excalibur/blob/master/STYLEGUIDE.md)
- [x] :triangular_ruler: new tests written and passing / old tests updated with new scenario(s)
- [ ] :page_facing_up: changelog entry added (or not needed)

==================

Closes #126

## Changes:

- Added `clone()` method to `AsepriteSpriteSheet`
- Added `clone()` method to `AsepriteResource`

--------------

The integration tests are failing for me on main:

```
Test: A Aseprite parsed resource
        Expect: Aseprite Loop Animation
[ERROR]: Image ./test/integration/images/expected.png did not match acutal ./test/integration/images/actual.png, 146 different!
```

but unit tests all pass.

I'm also willing to revert the commits for adding clone to `AsepriteResource`, but if we're okay with how it's implemented, I quite like having it. Cloning the resource over digging into the spritesheet/anims is much cleaner in usage.

### CODE REVIEW

**Comment by eonarheim** [comment]
@mattjennings I'll look into the integration test, I wouldn't have expected your changes to cause the failure. Possibly a browser/platform rendering difference? Looks like it passes in CI though.

**Comment by mattjennings** [comment]
If it passes in CI then great!

Yeah, I am not too sure what causes it. Smells like curse of the M1 Mac again... is there a way to know which browser `ex-test` uses?

Here are the expected/actual/diff images it produced:

expected
actual
diff-actual

**Comment by eonarheim** [comment]
@mattjennings  Agree, it's probably that M1 Mac issue we ran into on the main repo.

You ready for me to merge with CI passing?

>  is there a way to know which browser ex-test uses?

This is a good question, I'll poke around 👍

**Comment by mattjennings** [comment]
Yup it's good to go!

**Comment by eonarheim** [comment]
@mattjennings Thanks again!

**Pull request merged**
